NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 2000			--group moving and still units
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 2000			--group moving and still units
NDefines_Graphics.NGraphics.UNITS_ICONS_DISTANCE_CUTOFF = 2000
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 2000
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 2000
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 2000
NDefines_Graphics.NGraphics.FRIEND_COLOR  = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.ENEMY_COLOR   = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.NEUTRAL_COLOR = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.LAND_COMBAT_DISTANCE_CUTOFF = 0
NDefines_Graphics.NGraphics.NAVAL_COMBAT_DISTANCE_CUTOFF = 0
NDefines_Graphics.NGraphics.NAVAL_MISSION_ICONS_DISTANCE_CUTOFF = 0
NDefines_Graphics.NGraphics.SHOW_ONLY_PATH_ABOVE = 2000.0
NDefines.NGraphics.WEATHER_DISTANCE_CUTOFF = 0