NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {450, 800, 800}
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_DOT_CUTOFF_MAX = 800
NDefines_Graphics.NGraphics.CAPITAL_ICON_CUTOFF = 800