NDefines.NGame.END_DATE = "2199.1.1.1"

NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 900000
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 900000

NDefines_Graphics.NGraphics.UNITS_ICONS_DISTANCE_CUTOFF = 900000
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 900000
NDefines_Graphics.NGraphics.NAVALBASE_ICON_DISTANCE_CUTOFF = 20
NDefines_Graphics.NGraphics.AIRBASE_ICON_DISTANCE_CUTOFF = 20
NDefines_Graphics.NGraphics.RADAR_ICON_DISTANCE_CUTOFF = 20

NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {15, 25, 50}
NDefines_Graphics.NGraphics.VICTORY_POINTS_DISTANCE_CUTOFF = {25, 50, 100}

NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE_STRATEGIC = 0
NDefines_Graphics.NGraphics.MAP_ICONS_COARSE_COUNTRY_GROUPING_DISTANCE = 100

NDefines_Graphics.NGraphics.LAND_COMBAT_DISTANCE_CUTOFF = 20
NDefines_Graphics.NGraphics.NAVAL_COMBAT_DISTANCE_CUTOFF = 20