outdir=r"C:\Users\wgic\Documents\Paradox Interactive\Hearts of Iron IV\mod\Universal Unlock Units\uuu_core_ses.txt"
##在上面输入目标文件路径  Enter the target file path above👆

namelist=[

    ##原版名称

    "Guarnición Republicana",
    "Brigada de Juventudes Sindicales",
    "Mobile Headquarter",
    "West Africa Intervention Force",
    "Divisione Coloniale",
    "Central Africa Intervention Force",
    "Landstormen Militia",
    "SS Panzer Division",
    "SS Panzergrenadier Division (n.A.)",
    "Resistance Fighters",
    "Battaglione Azad Hindoustan",
    "Cavalleria Coloniale",
    "Workers Militia",
    "Landsturmregiment",
    "Hare Majesteits Duitse Legioen",
    "Central Africa Defense Force",
    "Japanese People's Regiment",
    "FFI Demi-Brigade",
    "Japanese Loyalist Regiment",
    "Swiss Citizen Militia",
    "Manchu Banner",
    "SS Motorisierte Division",
    "Kebur Zabagna",
    "Kongens Menn",
    "Silver Legion",
    "American Garrison",
    "Sudanese Mercenaries",
    "German Trained Division",
    "División de la Guardia de Asalto",
    "Black Lions",
    "Fatherland Front Partisans",
    "Truppe Irregolari a Cavallo",
    "Batalhões de Presos",
    "Carabineros Patrios de Chile",
    "International Marxist Brigades",
    "Syria Defense Force",
    "Arab Mercenaries",
    "Hemvärn",
    "Stormtrupper",
    "Neuvostoliiton Legioona",
    "Soviet Volunteers",
    "Shtrafnaya Chast",
    "Karjalan Metsäsissit",
    "NKVD Pogranichnaya Diviziya",
    "West Africa Defense Force",
    "Guards",
    "Redemption Army",
    "Tomislav's Royal Guards",
    "Leichte-Brigade",
    "Yugoslavian Defence Army",
    "Indochina Intervention Force",
    "Legion of the Damned",
    "Pakistani Liberation Army",
    "Camicie Nere",
    "Rangaistusdivisioona",
    "Camicie Rosse",
    "Irregular Cavalry Division",
    "Montenegrin Chetniks",
    "Brigada Legionario",
    "Makedonska Revolyutsionna Militsiya",
    "East African Irregulars",
    "SS Panzer Division (vollgep.)",
    "Blackshirt Brigade",
    "Danske Brigade",
    "Hemmelige Hæren",
    "Forest Brothers",
    "Divisione Ascari Libica",
    "Anarchist Militia",
    "Local Volunteers",
    "Opposition Partisan Brigade",
    "Divisione Ascari Somala",
    "Norsk Milits",
    "Hindu Militia",
    "Republican Guard",
    "Congolese Mercenaries",
    "Fake Intel Division",
    "Trotskyist Workers' Militia",
    "Bukharinist Peasant Militia",
    "Spanish Loyalist Division",
    "Bangladeshi Liberation Army",
    "Morges Division",
    "Brigada de la Guardia Civil",
    "Soviet Special Brigades",
    "International brigade",
    "Banda Irregolare Libica",
    "Banda Indigena Irregolare",
    "Loyalist Brigade",
    "Irregular Camelry Division",
    "Trotskyist Revolutionary Militias",
    "Modstandsbevægelsen Militia",
    "Voluntarios Argentinos",
    "Fatherland Front Militia",
    "Indochina Defense Force",
    "Hirden Milits",
    "Brigada Popular",
    "Chitet Sefari",
    "Fifth Columnist Brigade",
    "Bukharinist Workers' Militia",
    "Forsvarsmilitser",
    "Legião Estrangeira",
    "Banda Irregolare Eritrea",
    "Japanese Expeditionary Force",
    "Eritrean Askari",
    "Brigada Internacionales",
    "Integralist Militia",
    "Punakaarti",
    "SS Waffen-Grenadier-Division",
    "SS-Sturmbrigade",
    "Bristol Blenheim",
    "Rannikkorykmentti",
    "Peasant Militia",
    "Resistance",
    "Mustapaidat",
    "Arbegnoch Fighters",
    "Syria Intervention Force",
    "Carabineros",
    "Citizen Militia",
    "POUM Special Brigades",
    "Requeté Carlista",
    "Våpenfolket",
    "Folkets Hær",
    "Red Guards",
    "Exiles",
    "International Brigades",
    "SS Panzer Division (n.A.)",
    "Divisione Ascari Eritrea",
    "Divisione Partigiana",
    "Guarnición Nacionalista",
    "Brigada de las Juventudes del POUM",
    "Brigada Agrarista",
    "Truppe Irregolari di Cammelli",
    "Banda Irregolare Somala",
    "Ugonskrust Division",
    "SS Panzergrenadier Division",
    "Trotskyist Peasant Militia",
    "Anti-Exploit Punitive Brigade",
    "Brigada Anarquista",

    ##兼容mod————《人名和部队名称汉化 （只限原版）》[2067895531]

    "黑衫军旅",
    "女王陛下的德国军团",
    "共和国卫队",
    "巴基斯坦解放军",
    "秘密军队",
    "土著民兵师",
    "Swiss Citizen Militia",
    "印度民兵师",
    "国民卫队旅",
    "卡累利阿森林游击队",
    "保皇党师团",
    "Citizen Militia",
    "刚果雇佣军",
    "工人赤卫队",
    "孟加拉国解放军",
    "骆驼骑兵师",
    "阿拉伯雇佣军",
    "抵抗战士",
    "家园卫队",
    "国民警卫队",
    "托洛茨基主义工人民兵",
    "卡洛斯呼啸兵",
    "森林兄弟游击队",
    "托洛茨基主义农民民兵",
    "印度支那干涉部队",
    "殖民地骑兵队",
    "叙利亚防卫军",
    "西班牙卡洛斯保皇师",
    "武装部队",
    "利比亚殖民地师",
    "反剥削惩戒旅",
    "索马里民兵师",
    "突击卫队师",
    "Resistance",
    "印度支那防卫军",
    "防卫民兵",
    "苏联特种旅",
    "火十字团",
    "丹麦旅",
    "自由印度军团",
    "红衫军",
    "布里斯托尔 布伦海姆",
    "工人民兵",
    "民兵师",
    "南斯拉夫防卫军",
    "国际旅",
    "骑兵师",
    "芬兰黑衫军",
    "无政府主义民兵师",
    "索马里班队",
    "反对派游击队",
    "赤军",
    "无政府主义旅",
    "海岸兵团",
    "联合青年旅",
    "东非民兵师",
    "惩戒步兵师",
    "黑衫军",
    "统工党特战旅",
    "党卫军突击旅",
    "马其顿革命军",
    "抵抗军民兵",
    "FFI半旅团",
    "尼德兰国土风暴国民卫队",
    "利比亚民兵师",
    "苏联军团",
    "惩戒营",
    "步兵旅",
    "国际马克思主义旅",
    "囚犯营",
    "托米斯拉夫皇家卫队",
    "可移动总部",
    "荣誉卫队",
    "中非武装防卫军",
    "中部非洲干预部队",
    "民兵团",
    "国王军",
    "智利祖国警卫队",
    "党属民兵卫队",
    "日本远征军",
    "救赎军",
    "莫尔日师",
    "黑山切特尼克师",
    "共和警卫队",
    "美洲驻军",
    "非正规骆驼骑兵师",
    "布哈林农民民兵",
    "八旗师",
    "警卫",
    "忠良旅",
    "祖国阵线游击队",
    "本土志愿军",
    "抵抗军",
    "人民旅",
    "咒缚军团",
    "黑狮组织师",
    "厄立特里亚班队",
    "内务人民委员部边境卫队",
    "德国培训师",
    "厄立特里亚殖民地师",
    "叙利亚干预部队",
    "警卫团",
    "阿根廷志愿军",
    "冲锋队",
    "托洛茨基主义革命民兵",
    "挪威人民军",
    "外籍军团",
    "苏联志愿军",
    "银衫军团",
    "殖民地骑警师",
    "游击队",
    "厄立特里亚战士师",
    "祖国阵线民兵师",
    "切特师",
    "利比亚班队",
    "流亡者",
    "轻装旅",
    "统工党青年旅",
    "布哈林工人民兵",
    "第五纵队",
    "苏丹雇佣军",
    "疑兵师",
    "索马里殖民地师",
    "公民民兵",
    "西非国防军",
    "厄立特里亚民兵师",
    "殖民地驻军",
    "赤卫队",
    "西非干预部队",

    ##兼容mod————《The road to 56 CN》[2129897125]

    "Jōsetsu Shidan",
    "Fatherland Front Militia",
    "Irgenii Tsereg",
    "Iron Guard Brigade",
    "Opposition Partisan Brigade",
    "Leichte Brigade",
    "Congolese Mercenaries",
    "Trained Bergsteiger Brigade",
    "Black Shirts",
    "POUM Special Brigades",
    "Bukharinist Peasant Militia",
    "Maori Volunteers",
    "Banda Irregolare Somala",
    "Camicie Rosse",
    "Teritorijalna Odbrana",
    "Brigada Anarquista",
    "Local Volunteers",
    "Loyalist Milita",
    "Carabineros Patrios de Chile",
    "Riechskommissariat Garrison",
    "KPD Partisans",
    "Neuvostoliiton Legioona",
    "Divisione Coloniale",
    "Divisione Ascari Libica",
    "Cavalleria Coloniale",
    "Zwarte Brigade",
    "Redemption Army",
    "Rotes Regiment",
    "Makedonska Revolyutsionna Militsiya",
    "Trained Bergsteiger-Abteilung",
    "Guarnición Republicana",
    "Indochina Intervention Force",
    "Bangladeshi Liberation Army",
    "Punakaarti",
    "Frivilligregiment",
    "Trained Grenzbrigade",
    "Trotskyist Workers' Militia",
    "Mustapaidat",
    "Dangpai",
    "Georgian Volunteers",
    "Bergsteiger Brigade",
    "Arab Mercenaries",
    "International Brigades",
    "Rangaistusdivisioona",
    "Exiles",
    "Brigada de la Guardia Civil",
    "Rannikkorykmentti",
    "Hemvärn",
    "Volkssturm",
    "Irregular Cavalry Division",
    "National Defense Guard",
    "Anti-Exploit Punitive Brigade",
    "Landsturmregiment",
    "Sentinel of the Motherland",
    "Soviet Volunteers",
    "Chitet Sefari",
    "Trotskyist Peasant Militia",
    "Shtrafnaya Chast",
    "Azerbaijani Volunteers",
    "forsvarsmilitser",
    "Resistance Fighters",
    "Bergsteiger Grenzbrigade",
    "Stadtkommando",
    "Trained Infanterie-Abteilung",
    "Camicie Nere",
    "Armenian Volunteers",
    "International Marxist Brigades",
    "Ugonskrust Division",
    "Trained Leichte Brigade",
    "Carabineros",
    "Divisione Partigiana",
    "International brigade",
    "Sudanese Mercenaries",
    "Hare Majesteits Duitse Legioen",
    "Fatherland Front Partisans",
    "Guards",
    "SS-Sturmbrigade",
    "Indochina Defense Force",
    "West Africa Intervention Force",
    "Grenzbrigade",
    "Trained Stadtkommando",
    "GRVPN",
    "Japanese Expeditionary Force",
    "Silver Legion",
    "Ersatzheer",
    "Red Guards",
    "Defence Force",
    "Central Africa Defense Force",
    "Keibitai",
    "East African Irregulars",
    "Bukharinist Workers' Militia",
    "Trained Bergsteiger Grenzbrigade",
    "Truppe Irregolari di Cammelli",
    "Eritrean Askari",
    "Batalhões de Presos",
    "Stormtrupper",
    "American Garrison",
    "Pakistani Liberation Army",
    "Brigada Agrarista",
    "folkets hær",
    "Divisione Ascari Somala",
    "Milishia Qabalia",
    "NKVD Pogranichnaya Diviziya",
    "Modstandsbevægelsen Militia",
    "Central Africa Intervention Force",
    "Jaeger SS Division",
    "Montenegrin Chetniks",
    "Kebur Zabagna",
    "'Ansar Sudaniuwn",
    "Hirden Milits",
    "Manchu Banner",
    "Trotskyist Revolutionary Militias",
    "Irregular Camelry Division",
    "Hindu Militia",
    "Bristol Blenheim",
    "Banda Indigena Irregolare",
    "Elite Bergsteiger Grenzbrigade",
    "Kōdō Tai",
    "Banda Irregolare Libica",
    "Blackshirt Brigade",
    "Brigada de Juventudes Sindicales",
    "Danske Brigade",
    "Jaeger German Infanterie-Division",
    "West Africa Defense Force",
    "Resistance",
    "Black Lions",
    "Karjalan Metsäsissit",
    "Kuva-yi Milliye Tugayi",
    "Syria Intervention Force",
    "Truppe Irregolari a Cavallo",
    "Workers Militia",
    "Hemmelige Hæren",
    "Fedrelandsregiment",
    "Forest Brothers",
    "våpenfolket",
    "German Trained Division",
    "Anti-Nacistas Brigades",
    "Tomislav's Royal Guards",
    "Legião Estrangeira",
    "Loyalist Brigade",
    "Z Special Unit",
    "Elite Bergsteiger-Abteilung",
    "Kongens Menn",
    "Spanish Loyalist Division",
    "Fake Intel Division",
    "Fifth Columnist Brigade",
    "Anarchist Militia",
    "Mobile Headquarter",
    "Voluntarios Argentinos",
    "Peasant Militia",
    "Soviet Special Brigades",
    "Brigada de las Juventudes del POUM",
    "Bergsteiger-Abteilung",
    "Banda Irregolare Eritrea",
    "Saudi Korps",
    "Elite Bergsteiger Brigade",
    "Republican Guard",
    "Syria Defense Force",
    "Morges Division",
    "Independent Battalion",
    "Requeté Carlista",
    "División de la Guardia de Asalto",
    "Divisione Ascari Eritrea",
    "Elite Infanterie-Abteilung",
    "FFI Demi-Brigade",
    "Infanterie-Abteilung",
    "Brigada Popular",
    "Reserva",
    "Citizen Militia",
    "Tribal Levy",
    "Guarnición Nacionalista",

    ##兼容mod————《The road to 56 CN Supply | 56之路汉化补全》[3057351603]

    "惩戒师",
    "内务部边防师",
    "保皇党民兵师",
    "受训边境旅",
    "边防旅",
    "党卫军晚期装甲师",
    "西非国防军",
    "受训轻型旅",
    "党卫军摩托化步兵师",
    "苏联志愿军",
    "美国警备队",
    "丹麦旅",
    "统工党特战旅",
    "满洲八旗",
    "四单位制师团",
    "党卫军装甲掷弹兵师",
    "格鲁吉亚志愿军",
    "地下军",
    "无政府主义旅",
    "帝国总督府卫戍师",
    "反对派游击队",
    "叙利亚干涉军",
    "森林兄弟",
    "托洛茨基革命民兵师",
    "国民军",
    "国际旅",
    "东非非正规师",
    "第五纵队",
    "精锐边境山地师",
    "公民骑兵师",
    "非正规骆驼骑兵队",
    "孟加拉人民解放军",
    "武装党卫队",
    "赤卫军",
    "后备军",
    "志愿民兵团",
    "民族主义驻军师",
    "受训边境山地师",
    "救国军",
    "农民自卫军",
    "苏联军团",
    "刚果雇佣军",
    "山地旅",
    "轻型旅",
    "边防军",
    "外籍兵团",
    "民兵团",
    "无政府主义民兵",
    "精锐山地师",
    "印度支那国防军",
    "独立营",
    "阿拉伯雇佣军",
    "风暴民兵师",
    "Z特种部队",
    "非正规骆驼骑兵师",
    "布哈林派农民自卫军",
    "受训军团司令部",
    "保加利亚祖国阵线军",
    "国际志愿旅",
    "惩戒营",
    "步兵师",
    "帝国近卫师",
    "人民军预备役",
    "武装警察",
    "反纳粹旅",
    "女王陛下的德意志军团",
    "托派工人民兵",
    "卡累利阿森林游击队",
    "德共游击队",
    "沙特军",
    "流亡者",
    "毛利人志愿军",
    "马克思主义国际纵队",
    "党卫军装甲师",
    "日本远征军",
    "人民旅",
    "索马里民兵师",
    "亚美尼亚志愿军",
    "祖国哨兵",
    "黑衫军",
    "步兵旅",
    "国民警卫旅",
    "保皇旅",
    "军团司令部",
    "党卫军武装榴弹兵师",
    "咒缚军团",
    "党卫军突击旅",
    "工会青年",
    "德国训练师",
    "骑兵师",
    "叙利亚国防军",
    "公民自卫军",
    "保加利亚祖国阵线游击队",
    "反剥削惩戒旅",
    "沿海步兵团",
    "党派",
    "突击师",
    "共和国卫队",
    "西班牙独立师",
    "党属卫队民兵师",
    "纳粹党",
    "苏联特战旅",
    "受训山地旅",
    "疑兵师",
    "民兵抵抗师",
    "布哈林派工人民兵",
    "精锐山地旅",
    "统工党青年旅",
    "智利卡宾枪爱国骑兵",
    "印度支那干涉军",
    "中非干涉军",
    "向部落征兵",
    "铁卫团",
    "边境山地师",
    "党卫军精锐装甲师",
    "莫尔日阵线步兵师",
    "殖民地骑兵师",
    "抵抗战士",
    "托米斯拉夫近卫军",
    "国民突击队",
    "山地师",
    "布里斯托尔“布伦海姆”重型战斗机",
    "秘密抵抗组织",
    "警备队",
    "非正规骑兵师",
    "卡洛斯呼啸兵",
    "防卫师",
    "法兰西内地军半旅",
    "黑衫旅",
    "祖国团",
    "瑞士公民师",
    "Rotes Regiment",
    "阿根廷志愿军",
    "西非干涉军",
    "赤卫队",
    "受训步兵师",
    "厄立特里亚阿拉伯步兵师",
    "受训山地师",
    "人民军",
    "阿塞拜疆志愿军",
    "突击近卫师",
    "非正规师",
    "党卫军精锐装甲掷弹兵师",
    "马其顿革命军",
    "银衫军",
    "黑人旅",
    "中非国防军",
    "本地志愿军",
    "利比亚民兵师",
    "厄立特里亚民兵师",
    "巴基斯坦解放军",
    "轻装旅",
    "国防军",
    "烈焰十字军",
    "红衫军",
    "契特守卫师",
    "行动队",
    "托派农民自卫军",
    "机动司令部",
    "黑山祖国军",
    "德意志猎兵师",
    "土著民兵师",
    "爱国者联盟斗士军",
    "游击师",
    "国王扈从师",
    "志愿团",
    "精锐步兵师",
    "苏丹雇佣兵",
    "黑狮军",
    "国民警卫队",
    "共和驻军师",
    "预备师",
    "工人民兵师",
    "印度民兵",

    ##兼容mod————《Equestria at War》[1826643372]

    "Division of the North",
    "Pegasi Sky Phalanx",
    "PCA Militia",
    "Brodfeld's Civilians",
    "Paratroopers",
    "Golden-Horn Militia",
    "Wordbearers",
    "Herzland Landsknechte",
    "Mobile Desert Corps Infantry Division",
    "Sisters of Eyr",
    "Capital Assurance Unit",
    "Tribal War Party",
    "Slingtails",
    "Seafarer Banner",
    "Militia Division",
    "Rural Mob",
    "Guild Security Squadron",
    "Zrakoplovni Regiment za Specijalne Operacije",
    "Peasant Group",
    "Colthaginian Mercenaries",
    "Changeling Expeditionary Corps",
    "Corporate Para-Motorized Unit",
    "Peasant Militia",
    "Lushian Hussars",
    "Guardia Rossa",
    "Volunteer Militia",
    "Red Battalion",
    "Mercenary Panzers",
    "Feudal Levy",
    "Fake Intel Division",
    "CSI Cave Defense",
    "Unemployed Squatters",
    "Volunteer Peasants",
    "Canterlot Guard",
    "Territorial Volunteers",
    "Solar Guard",
    "Hydras",
    "Worker Militia",
    "Integruota spec. operacijų divizija",
    "Loyalist Brigade",
    "Hetmanate Loyalists",
    "Cultist Brigade",
    "Righteous Vanguards",
    "Regulars",
    "Lunar Imperial Guard",
    "Prolguard",
    "Panzergrenadier Division",
    "Elite Security Squadron",
    "Mercenary Knights",
    "Lithuanian Leopold",
    "Order Militant",
    "Changeling Scouts",
    "Dragon Mercenaries",
    "Mercenary Hoplites",
    "Sons of Arcturius",
    "Diamond Dog Mercenaries",
    "Freikorps",
    "Riverlander Mercenaries",
    "Knightly Order",
    "Lushian Levy",
    "Titan",
    "Mobile Desert Corps Armoured Division",
    "Jade Company Division",
    "Gallowglasses",
    "Chimeras",
    "Helot Rebels",
    "Motorized Security Squadron",
    "Free Pony Militia",
    "Tatzlwurms",
    "Heavy Security Squadron",
    "The Riesigerkatzenpanzer",
    "Kasan Volunteer Division",
    "Prisoner Brigade",
    "Noblepony Group",
    "Saint-Soldier Recruits",
    "Hippogriffian Volunteers",
    "Resistance",
    "Free Lances",
    "Brodfeld's Workers",
    "Blacktalon Band",
    "Wittenlandic Fyrd",
    "Canterlot Garrison",
    "Jager Division",
    "Anti-Exploit Punitive Brigade",
    "Experimental Armoured Brigade",
    "Thestral Jagers",
    "Izvidničke Snage",
    "Nirik Band",
    "Coltvan Mercenaries",
    "Corporate Para-Militia",
    "Volunteers",
    "Inquisitors",
    "Imperial Guard Division",
    "Arcturian Knights",
    "Incendiary Banner",
    "Coltjun Militia",
    "Sicameon Privateers",
    "Militiakirin Banner",
    "Tribal Warband",
    "Brodfeld's Unemployed",
    "Riječni Zračni i Kopneni Timovi",
    "Adelart Forest Brothers",
    "Somatophylakes",
    "Leopold Schmeller",
    "Corporate Para-Mechanized Unit",
    "Blackhollow Highwaygriffs",
    "Warzenan Liberation Army Division",
    "Stalwarts",
    "Free Griffon Division",
    "Sombra's Royal Guards",
    "Frontier Banner",
    "Lockstep Legion",
    "Manticores",
    "Oi Myrioi",
    "Jagdkommando Einsatzgruppe",
    "Loyalist Militia",
    "Freie Reiter",
    "OOSSR",
    "Elder Dragon",
    "Kirin Volunteers",
    "Mercenary Ironpaws",
    "FAINN Division",
    "Ali Nere",
    "Foreign Legion",
    "Lan Kir War-Banner",
    "Las Pegasus National Guard",
    "Tamed Dragons",
    "Chiropterran Expeditionary Corps",
    "Mercenary Chargers",
    "Bloedjagers",
    "Forced Conscripts",
    "Abiyot Yennterib",
    "Army Civic",
    "Crumbling Zombies",
    "Commune Militia",
    "Infiltrator-Saboteurs",
    "Partisans",
    "Wingbardian Condottieri",
    "Imperial Eastern Expeditionary Force",
    "Rural Levy",
    "Bernier",
    "Banner Veterans",
    "Fascist Militia",
    "Mercenary Cossacks",
    "FIRCWMilitia",
    "CLA Militia",
    "International Brigades",
    "Brigata Carabinieri",
    "Last Warband",

    ##兼容MOD——《The New Order: Last Days of Europe》[2438003901]
    "Custom TNO Division",
    "Narodnaya Mekhanizirovanaya Batalon",
    "Brigada de Legionarios",
    "Marine Brigade",
    "Rehimen",
    "Territorialetruppe",
    "Teishin Shudan",
    "Infantry Division",
    "Milícia de Reserva Nacional",
    "Columna Legionaria",
    "Heimevernet",
    "Infantry Brigade",
    "(spz.) Marineabteilung",
    "Milis Revolisyonè",
    "Peasant Militia",
    "Milicia Nacional",
    "Brigada Rebelde del Ejército",
    "GSSN Skidivisjon",
    "Brigadang Makapili",
    "Brigada Mixta",
    "Fizarana Infantry",
    "Compañía Blindada Revolucionaria",
    "(spz.) Fallschirmjägerabteilung",
    "Guardia Civil Ibérica",
    "Schutztruppe",
    "Coluna Infernal",
    "Brigada de Reserva",
    "(spz.) Panzergrenadierabteilung",
    "Rengou Tokubetsu Rikusentai",
    "Disband Inf",
    "Brigada del Ejército",
    "Armored Brigade",
    "Infanterie-Division",
    "División Voluntaria",
    "Waffen-SS",
    "Dibisyong Pampangulo",
    "Gardia Nacional",
    "American Volunteer Infantry Division",
    "Unité de Défense Territoriale",
    "National Guard Infantry Division",
    "Sandatahang Pangkat",
    "Japanese Volunteers",
    "Shuebat Alnizamia",
    "Légion Española",
    "Brigada de la Reserva Federal de Emergencia",
    "Brigada Ecuatorial",
    "Experimental Helicopter Division",
    "Milizia Brigada",
    "Brigada Vermelha",
    "Narodnaya Oborony Otrjad",
    "American Volunteer Marine Division",
    "Brigada Argentina",
    "Shturmoviki Otrjad",
    "Airborne Brigade",
    "Guardia Presidencial",
    "Fake Intel Division",
    "West African Expeditionary Force",
    "Experimental Rifle Division",
    "GSSN Divisjon",
    "Canadian Expeditionary Light Infantry",
    "Light Division",
    "Xikang Zhìyuàn zhě",
    "Disband",
    "Hirdregiment",
    "Hohei Shidan",
    "Konoe Shidan",
    "Armoured Infantry",
    "Home Guard",
    "Panzergrenadier-Division",
    "Volontaires de la France Libre",
    "Columna Blindada Legionaria",
    "Reziman'ny Mpikomy",
    "Sicherungsdivision",
    "Garde Rouj",
    "Infantry Regiment",
    "Bubing Shi",
    "Experimental SPART Division",
    "Mechanized Brigade",
    "Dokuritsu Konsei Ryodan",
    "Brigadang Pamayapa",
    "Partisan Group",
    "Reservetruppen",
    "Anti-Exploit Punitive Brigade",
    "Reziman'ny an-Tendrombohitra",
    "Rikugun Shidan - Army Division",
    "Tercio de Extranjeros",
    "Guomin Jiefang Jun",
    "Auxillary Brigade",
    "Konoe Sensha Shidan",
    "Motorized Division",
    "American Volunteers to Iran",
    "Mountaineer Division",
    "Batallon Expedicionario Revolucionario",
    "Panzer-Division",
    "Experimental MBT Division",
    "Ad-Hoc Milita",
    "Shuzui Jun",
    "Canadian Expeditionary Force",
    "Northumberland County Division",
    "Geriya Revolisyonè",
    "Jingwei Shi",
    "National Guard Armored Division",
    "Shuzui Juntuan",
    "Legión Dominicana",
    "Kollaboratorenbrigade",
    "Marine-Abteilung Unit",
    "Militia",
    "Territorialnoy Oborony Batalon",
    "Chernaya Gvardiya",
    "Jingrui Jingwei Shi",
    "Honourable Artillery Company",
    "Compagnie de Gendarmerie",
    "ANZAC Battle Group",
    "Nacionalnaya Gvardiya Otrjad",
    "(spz.) Panzerabteilung",
    "Royal African Rifles",
    "Royal Military Police",
    "Liwa' Almsha",
    "Peasant Divisions",

]



import codecs
import time

start = time.time()
namelistone = list(set(namelist))
print(len(namelist),len(namelistone))
with codecs.open(outdir,"w","utf-8") as file:
    file.write("""uuu_core_eff = {
	country_lock_all_division_template = no\n""")
    for name in namelistone:
        file.write("""	if = {
		limit = { has_template = """+"\""+name+"\""+""" }
		set_division_template_lock = { division_template = """+"\""+name+"\""+""" is_locked = no }
		clear_division_template_cap = { division_template = """+"\""+name+"\""+""" }
	}
  """)  
    file.write("}")
end = time.time()
print("Using time: "+str(end - start)+"s")